SECRET_KEY = 'YOUR SECRET KEY'

USER_EXT_CONF_URL = 'YOUR OAUTH CONF URL'
USER_EXT_CLIENT_ID = 'YOUR OAUTH CLIENT ID'
USER_EXT_CLIENT_SECRET = 'YOUR OAUTH CLIENT SECRENT'
USER_EXT_JWT_SECRET = b'YOUR JWT SECRET'

SONG_EXT_CLIENT_ID = 'YOUR SPOTIFY CLIENT ID'
SONG_EXT_CLIENT_SECRET = 'YOUR SPOTIFY CLIENT SECRET'
SONG_EXT_DOWNLOADED_SONGS_DIRECTORY = "./downloaded"
SONG_EXT_USERNAME = 'YOUR SPOTIFY USERNAME'
SONG_EXT_PASSWORD = 'YOUR SPOTIFY PASSWORD'
